name: stafivo_mobile
description: "STAFIVO – Smart Workforce. Seamless Operations."
# Built by Pent 26
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.3
  camera: ^0.11.2+1
  google_mlkit_face_detection: ^0.13.1
  geolocator: ^14.0.2
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.2
  sqflite: ^2.4.2
  flutter_dotenv: ^6.0.0
  http: ^1.2.2
  image: ^4.2.0
  tflite_flutter: ^0.12.1
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/models/mobilefacenet.tflite
    - assets/stafivo_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/stafivo_logo.png
  adaptive_icon_foreground: assets/stafivo_logo.png
  adaptive_icon_background: "#0F3D91"
  remove_alpha_ios: true
  min_sdk_android: 21
